---
- name: "Configure Cisco Router" 
  hosts: routers
  gather_facts: no
  become: yes

  tasks:
    - name: "Configure Gi1 with IP address"
      cisco.ios.ios_config:
        name: GigabitEthernet1
        description: "Configured via Ansible"
        enabled: yes
        state: present

    - name: "Assign IP address to Gi1"
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.189.126 255.255.255.0
        parents: interface GigabitEthernet1
      notify: save config

    - name: Configure DHCP Pool
      cisco.ios.ios_config:
        lines:
          - network 192.168.189.0 255.255.255.0
          - default-router 192.168.189.2
          - dns-server 8.8.8.8
          - domain-name example.local
        parents: ip dhcp pool LAN

    - name: "Backup running-config"
      cisco.ios.ios_config:
        commands: show running-config
      register: running_config

    - name: Save backup to local file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "./backup/running-config-{{ inventory_hostname }}.txt"

  handlers:
    - name: save config
      ios_config:
        save_when: modified
