--- 

- name: Deploy Cacti on Linux servers
  become: yes
  hosts: webservers
  tasks:
  
    - name: Launch cact docker container
      docker_container:
         name: cacti-server
         image: "million12/mariadb"
         pull: true
         networks_cli_compatible: yes
 services:
  db:
    container_name: db
    image: million12/mariadb
    environment:
      MARIADB_USER: cactiuser
      MARIADB_PASS: my_password
  cacti:
    image: polinux/cacti
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_USER: cactiuser
      DB_PASS: my_password
      DB_ADDRESS: db
