---
- name: Deploy Cacti on Linux servers
  become: yes
  hosts: webservers
  tasks:

    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Create a directory for Cacti deployment
      file:
        path: /opt/cacti
        state: directory
        mode: '0755'

    - name: Create docker-compose.yml file
      copy:
        dest: /opt/cacti/docker-compose.yml
        content: |
          version: '3'
          services:
            db:
              container_name: db
              image: million12/mariadb
              environment:
                MARIADB_USER: cactiuser
                MARIADB_PASS: my_password
            cacti:
              image: polinux/cacti
              ports:
                - "80:80"
                - "81:81"
                - "443:443"
              environment:
                DB_USER: cactiuser
                DB_PASS: my_password
                DB_ADDRESS: db
        mode: '0644'

    - name: Start Cacti using Docker Compose
      command:
        cmd: docker-compose up -d
        chdir: /opt/cacti
