---
- name: Deploy Cacti using Docker Compose
  become: yes
  hosts: linux_webservers
  tasks:

    - name: Install Docker Compose (if needed)
      apt:
        name: docker-compose
        state: present
      notify:
        - run-docker-compose-cacti

    - name: Copy docker-compose.yml to server
      copy:
        src: docker-compose.yml
        dest: /home/ansible/cacti/docker-compose.yml
        mode: '0644'
      notify:
        - run-docker-compose-cacti

  handlers:
    - name: run-docker-compose-cacti
      docker_compose:
        project_src: /home/ansible
        state: present
