---
- name: Deploy Cacti and manage packages
  become: yes
  hosts: linux_webservers
  tasks:
    - name: Install packages
      apt:
        pkg:
          - vim
          - ncdu
        state: present
    
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
    
    - name: Install Docker-Compose
      apt:
        name: docker-compose
        state: present
    
    - name: Create user 'kaas'
      user:
        name: kaas
        state: present
        createhome: yes
        shell: /bin/bash
    
    - name: Install unattended-upgrades
      apt:
        name: unattended-upgrades
        state: present

    - name: Copy docker-compose.yml to server
      copy:
        src: docker-compose.yml
        dest: /home/ansible/
        mode: '0644'

    - name: Run docker-compose to start Cacti
      docker_compose:
        project_src: /home/ansible/
        state: present

  handlers:
    - name: apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Change hostname
      hostname:
        name: "{{ ansible_hostname }}-new"
      notify:
        - apt-get update
